availableSecrets:
  secretManager:
    - versionName: projects/772190012442/secrets/SERVER_URL/versions/latest
      env: SECRET_SERVER_URL
    - versionName: projects/772190012442/secrets/GOOGLE_MAPS_API_KEY/versions/latest
      env: SECRET_GOOGLE_MAPS_API_KEY
    - versionName: projects/772190012442/secrets/SOCKET_SERVER_URL/versions/latest
      env: SECRET_SOCKET_SERVER_URL

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - "-c"
      - |
        echo "API_SERVER_URL=$$SECRET_SERVER_URL" >> .env.production
        echo "NEXT_PUBLIC_API_SERVER_URL=$$SECRET_SERVER_URL" >> .env.production
        echo "NEXT_PUBLIC_CALLBACK_URL=https://planpal-client-772190012442.asia-northeast3.run.app/oauth/google/callback" >> .env.production
        echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$$SECRET_GOOGLE_MAPS_API_KEY" >> .env.production
        echo "NEXT_PUBLIC_SOCKET_SERVER_URL=$$SECRET_SOCKET_SERVER_URL" >> .env.production
    secretEnv:
      [
        "SECRET_SERVER_URL",
        "SECRET_GOOGLE_MAPS_API_KEY",
        "SECRET_SOCKET_SERVER_URL",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-client/planpal-client:$SHORT_SHA",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-client/planpal-client:$SHORT_SHA",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "planpal-client",
        "--image",
        "asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-client/planpal-client:$SHORT_SHA",
        "--region",
        "asia-northeast3",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]

images:
  - "asia-northeast3-docker.pkg.dev/gen-lang-client-0798322573/planpal-client/planpal-client:$SHORT_SHA"
